# Generated by Django 5.1.2 on 2025-07-30 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contractor', 'Contractor')], max_length=20)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('date_of_birth', models.DateField()),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('hire_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_document', models.FileField(upload_to='id_documents/')),
                ('contract_document', models.FileField(upload_to='contracts/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_employees.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('license_type', models.CharField(max_length=50)),
                ('license_expiry', models.DateField()),
                ('vehicle_number', models.CharField(max_length=100)),
                ('insurance_number', models.CharField(max_length=100)),
                ('insurance_expiry', models.DateField()),
                ('total_deliveries', models.IntegerField()),
                ('average_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='_employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('junior', 'Junior Manager'), ('mid', 'Mid-level Manager'), ('senior', 'Senior Manager'), ('executive', 'Executive Manager')], max_length=20)),
                ('budget_limit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to='_employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='StoreStaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('is_shift_supervisor', models.BooleanField(default=False)),
                ('food_safety_cert', models.BooleanField(default=False)),
                ('food_safety_expiry', models.DateField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_staff_profile', to='_employees.employee')),
            ],
        ),
    ]
