# Generated by Django 5.1.2 on 2025-09-10 06:26

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_accounts', '0004_pendingsignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('website', models.URLField(blank=True)),
                ('company_number', models.CharField(blank=True, max_length=64)),
                ('vat_number', models.CharField(blank=True, max_length=64)),
                ('tax_id', models.CharField(blank=True, max_length=64)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='United Kingdom', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('currency_code', models.CharField(default='GBP', max_length=3)),
                ('timezone', models.CharField(default='Europe/London', max_length=64)),
                ('invoice_prefix', models.CharField(default='INV', max_length=20)),
                ('invoice_footer', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uniq_company_name_lower'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_company')],
            },
        ),
    ]
