# Generated by Django 5.1.2 on 2025-10-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_accounts', '0006_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessageActive',
            fields=[
            ],
            options={
                'verbose_name': 'Contact message (active)',
                'verbose_name_plural': 'Contact messages (active)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('_accounts.contactmessage',),
        ),
        migrations.CreateModel(
            name='ContactMessageArchived',
            fields=[
            ],
            options={
                'verbose_name': 'Contact message (archive)',
                'verbose_name_plural': 'Contact messages (archive)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('_accounts.contactmessage',),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
