# Generated by Django 5.1.2 on 2025-11-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_accounts', '0008_address_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(max_length=20),
        ),
    ]
