# Generated by ChatGPT on 2026-03-10

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_accounts', '0009_alter_address_house_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='uniq_user_email_lower',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower('email'),
                condition=models.Q(email__isnull=False) & ~models.Q(email__iexact='primaszecsi@gmail.com'),
                name='uniq_user_email_lower_except_test',
            ),
        ),
        migrations.RemoveConstraint(
            model_name='pendingsignup',
            name='uniq_pending_email_lower',
        ),
        migrations.AddConstraint(
            model_name='pendingsignup',
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower('email'),
                condition=models.Q(email__isnull=False) & ~models.Q(email__iexact='primaszecsi@gmail.com'),
                name='uniq_pending_email_lower_except_test',
            ),
        ),
    ]
