# Generated by Django 5.1.2 on 2026-04-14 08:15

import _accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_accounts', '0011_referrals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=_accounts.models.generate_referral_code, editable=False, max_length=10, unique=True),
        ),
    ]
