# Generated by Django 5.1.2 on 2025-07-30 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga_product_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('main_category', models.CharField(blank=True, max_length=255)),
                ('sub_category', models.CharField(blank=True, max_length=255)),
                ('sub_subcategory', models.CharField(blank=True, max_length=255)),
                ('variant', models.CharField(blank=True, max_length=255, null=True)),
                ('list_position', models.PositiveIntegerField()),
                ('url', models.URLField()),
                ('image_url', models.URLField(blank=True, db_index=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('rsp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promotion_end_date', models.DateField(blank=True, null=True)),
                ('multi_buy', models.BooleanField(default=False)),
                ('retail_EAN', models.CharField(blank=True, max_length=13)),
                ('vat_rate', models.CharField(choices=[('standard', 'Standard'), ('reduced', 'Reduced'), ('zero', 'Zero'), ('exempt', 'Exempt')], default='standard', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Labels_For_Searchbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels', models.TextField(blank=True, help_text='Space-separated search labels derived from ga_product_id and category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_labels', to='_catalog.all_products')),
            ],
        ),
    ]
