# Generated by Django 5.1.2 on 2025-10-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1', models.CharField(help_text='Parent category name, matches All_Products.sub_category', max_length=255)),
                ('l2', models.CharField(help_text='Subcategory name, matches All_Products.sub_subcategory', max_length=255)),
                ('display_name', models.CharField(blank=True, help_text='Optional override for the label shown on the tile', max_length=255)),
                ('image_url', models.URLField(blank=True, help_text='Optional image to use; falls back to first product image if empty')),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'l1', 'l2'),
                'unique_together': {('l1', 'l2')},
            },
        ),
    ]
