# Generated by Django 5.1.2 on 2024-12-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_catalog', '0002_rename_weight_product_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga_product_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=255)),
                ('variant', models.CharField(blank=True, max_length=255, null=True)),
                ('list_position', models.PositiveIntegerField()),
                ('url', models.URLField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('rsp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('promotion_end_date', models.DateField(blank=True, null=True)),
                ('multi_buy', models.BooleanField(default=False)),
                ('retail_EAN', models.CharField(blank=True, max_length=13)),
                ('vat_rate', models.CharField(choices=[('standard', 'Standard'), ('reduced', 'Reduced'), ('zero', 'Zero')], default='standard', max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
