# Generated by Django 5.1.2 on 2025-10-15 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_catalog', '0002_homesubcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homesubcategory',
            options={'ordering': ('sort_order', 'l1', 'l2'), 'verbose_name': 'Home subcategory', 'verbose_name_plural': 'Home subcategories'},
        ),
    ]
