# Generated by Django 5.1.2 on 2025-10-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_catalog', '0003_alter_homesubcategory_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeSubcategory',
        ),
    ]
