# Generated by Django 5.1.2 on 2025-10-25 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_catalog', '0004_delete_homesubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_ProductsMissingRSP',
            fields=[
            ],
            options={
                'verbose_name': 'Product with missing RSP',
                'verbose_name_plural': 'Products with missing RSP',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('_catalog.all_products',),
        ),
    ]
