# Generated by Django 5.1.2 on 2024-12-06 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_catalog', '0004_alter_category_options_remove_category_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Labels_For_Searchbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels', models.TextField(blank=True, help_text='Space-separated search labels derived from ga_product_id and category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_labels', to='_catalog.all_products')),
            ],
        ),
    ]
