# Generated by Django 5.1.2 on 2024-12-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_catalog', '0005_product_labels_for_searchbar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_products',
            name='vat_rate',
            field=models.CharField(choices=[('standard', 'Standard'), ('reduced', 'Reduced'), ('zero', 'Zero'), ('exempt', 'Exempt')], default='standard', max_length=10),
        ),
    ]
