# Generated by Django 5.1.2 on 2025-04-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_catalog', '0007_alter_all_products_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='all_products',
            name='category',
        ),
        migrations.AddField(
            model_name='all_products',
            name='main_category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='all_products',
            name='sub_category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='all_products',
            name='sub_subcategory',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
