# Generated by Django 5.1.2 on 2025-11-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_catalog', '0009_alter_homecategorytile_l1_and_l2'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homecategorytile',
            unique_together=set(),
        ),
    ]
