# Generated by Django 5.1.2 on 2025-11-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_catalog', '0013_merge_categorynodesetting_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorynodesetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
