# Generated by Django 5.1.2 on 2026-03-15 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_catalog', '0015_seed_basket_reward_pillar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCategoryTileFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1', models.CharField(max_length=255)),
                ('l2', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_category_tile_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Home category tile favorite',
                'verbose_name_plural': 'Home category tile favorites',
                'unique_together': {('user', 'l1', 'l2')},
            },
        ),
    ]
