# Generated by Django 5.1.2 on 2026-03-15 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_catalog', '0016_homecategorytilefavorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_entries', to='_catalog.all_products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product favorite',
                'verbose_name_plural': 'Product favorites',
                'unique_together': {('user', 'product')},
            },
        ),
    ]
