# Generated by Django 5.1.2 on 2025-12-30 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='visit',
            new_name='Danalytics__session_87cc58_idx',
            old_name='_analytics_v_session_28884e_idx',
        ),
    ]
