# Generated by Django 5.1.2 on 2026-03-18 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_analytics', '0003_analytics_foundation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='Danalytics__event_t_3e63c3_idx',
            old_name='analytics_ev_type_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='Danalytics__session_038a79_idx',
            old_name='analytics_ev_session_idx',
        ),
        migrations.RenameIndex(
            model_name='visitpageview',
            new_name='Danalytics__visit_i_911894_idx',
            old_name='analytics_vp_visit_idx',
        ),
        migrations.RenameIndex(
            model_name='visitpageview',
            new_name='Danalytics__path_2eec11_idx',
            old_name='analytics_vp_path_idx',
        ),
        migrations.RenameIndex(
            model_name='visitpageview',
            new_name='Danalytics__session_a82218_idx',
            old_name='analytics_vp_session_idx',
        ),
    ]
