# Generated by Django 5.1.2 on 2026-03-29 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_analytics', '0004_rename_analytics_ev_type_idx_danalytics__event_t_3e63c3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAdsLandingArrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('path', models.CharField(blank=True, db_index=True, max_length=2048)),
                ('arrived_at', models.DateTimeField(db_index=True)),
                ('traffic_source', models.CharField(blank=True, choices=[('direct', 'Direct'), ('search', 'Search'), ('social', 'Social'), ('email', 'Email'), ('campaign', 'Campaign'), ('referral', 'Referral'), ('unknown', 'Unknown')], db_index=True, max_length=20)),
                ('device_type', models.CharField(blank=True, choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('other', 'Other')], db_index=True, max_length=20)),
                ('browser_family', models.CharField(blank=True, db_index=True, max_length=50)),
                ('is_authenticated', models.BooleanField(db_index=True, default=False)),
                ('utm_source', models.CharField(blank=True, db_index=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, db_index=True, max_length=255)),
                ('referrer_host', models.CharField(blank=True, db_index=True, max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='google_ads_landing_arrivals', to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_ads_arrival', to='_analytics.visit')),
            ],
            options={
                'ordering': ('-arrived_at',),
                'indexes': [models.Index(fields=['path', 'arrived_at'], name='Danalytics__path_0442c5_idx'), models.Index(fields=['session_key', 'arrived_at'], name='Danalytics__session_d424cb_idx')],
            },
        ),
    ]
