# Generated by Django 5.1.2 on 2025-01-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_orders', '0003_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
