# Generated by Django 5.1.2 on 2025-03-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='supplier_completed',
            field=models.BooleanField(default=False, help_text="Mark if we've already ordered this item from suppliers."),
        ),
    ]
