# Generated by Django 5.1.2 on 2025-11-17 12:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_product_management', '0002_leafletcopy_default_site_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcategoryPipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('from_step', models.CharField(blank=True, max_length=64)),
                ('to_step', models.CharField(blank=True, max_length=64)),
                ('steps', models.TextField(blank=True, help_text='Comma-separated list of step names executed in this run.')),
                ('succeeded', models.BooleanField(default=False)),
                ('errors', models.TextField(blank=True, help_text='Captured error messages for this pipeline run (if any).')),
            ],
            options={
                'verbose_name': 'Subcategory pipeline run',
                'verbose_name_plural': 'Subcategory pipeline runs',
                'ordering': ('-started_at',),
            },
        ),
    ]
