# Generated by Django 5.1.2 on 2026-09-22 18:20

import uuid
from django.db import migrations, models


def populate_attempt_keys(apps, schema_editor):
    Payment = apps.get_model('_payments', 'Payment')
    for payment in Payment.objects.using(schema_editor.connection.alias).all().iterator():
        Payment.objects.using(schema_editor.connection.alias).filter(pk=payment.pk).update(attempt_key=uuid.uuid4())


class Migration(migrations.Migration):

    dependencies = [
        ('_payments', '0002_alter_payment_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='attempt_key',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(populate_attempt_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='payment', name='attempt_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='created', max_length=20),
        ),
    ]
